
package GUI;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author lenovo
 */
public class AnalysisGUI extends javax.swing.JFrame {

    /**
     * Creates new form AnalysisGUI
     */
    int dataSet[][] = new int[2][10];
    XYSeriesCollection collect;
    final static int countAlgo = 4;
    String [] algoList = new String[]{"RSA", "AES", "BlowFish", "DES"};
    
    public AnalysisGUI() {
        initComponents();
        
        //algoList =  new String[countAlgo];
        //plotGraph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RSACheck = new javax.swing.JCheckBox();
        AESCheck = new javax.swing.JCheckBox();
        BlowFishCheck = new javax.swing.JCheckBox();
        DESCheck = new javax.swing.JCheckBox();
        plotGraphButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CryptoSimulator");
        setResizable(false);

        RSACheck.setText("RSA");
        RSACheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSACheckActionPerformed(evt);
            }
        });

        AESCheck.setText("AES");

        BlowFishCheck.setText("BlowFish");

        DESCheck.setText("DES");

        plotGraphButton.setText("Plot Graph");
        plotGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotGraphButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Module");

        jMenuItem1.setText("Simulation");
        jMenuItem1.setSelected(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Analysis");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("Documentation");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Help");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RSACheck)
                            .addComponent(plotGraphButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AESCheck)
                            .addComponent(BlowFishCheck)
                            .addComponent(DESCheck))
                        .addGap(826, 826, 826))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RSACheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AESCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlowFishCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DESCheck)
                        .addGap(18, 18, 18)
                        .addComponent(plotGraphButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        SimulateGUI.simulateGUI.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RSACheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSACheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSACheckActionPerformed

    private void plotGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotGraphButtonActionPerformed
        int i, j;
        collect = new XYSeriesCollection();
        if(RSACheck.isSelected()){
            collect.addSeries(Algorithms.Asymmetric.RSA.getDataSet());
            
        }
        if(AESCheck.isSelected()){
            collect.addSeries(Algorithms.Symmetric.AES.getDataSet());
        }
        if(BlowFishCheck.isSelected()){
            collect.addSeries(Algorithms.Symmetric.BlowFish.getDataSet());
        }
        if(DESCheck.isSelected()){
           collect.addSeries(Algorithms.Symmetric.DES.getDataSet()); 
        }
        plotGraph();
    }//GEN-LAST:event_plotGraphButtonActionPerformed

  
    
    

    public void plotGraph(){
       
        
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Analysis of Algorithm",
                "memory",
                "time",
                collect,
                PlotOrientation.VERTICAL,
                true,
                true,
                true
        );
        
       try {
           ChartUtilities.saveChartAsJPEG(new File("G:\\chart.jpg"), chart, 500, 300);
           showImage();
       } catch (IOException ex) {
           Logger.getLogger(SimulateGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       
    }
    
    public void showImage() throws IOException{
        BufferedImage image = ImageIO.read(new File("G:\\chart.jpg"));
        ImageIcon icon = new ImageIcon(image);
        jLabel1.setIcon(icon);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AESCheck;
    private javax.swing.JCheckBox BlowFishCheck;
    private javax.swing.JCheckBox DESCheck;
    private javax.swing.JCheckBox RSACheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton plotGraphButton;
    // End of variables declaration//GEN-END:variables
}
