/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Algorithms.CrypticAlgo;
import Algorithms.CrypticObject;
import java.awt.Dimension;

import java.awt.image.BufferedImage;

import java.io.File;
import java.io.FileInputStream;

import java.io.IOException;

import java.security.Security;

import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

import javax.xml.bind.DatatypeConverter;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeriesCollection;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author Sneh
 */


public class AppGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppGUI
     */
    
   String plainText;
   String technique;
   String algo_used;
   String asym[] = new String[] { "RSA", "ElGamal", "Elliptic-Curve"};
   String sym[] = new String[] { "BlowFish", "DES", "AES" };
   String hash[] = new String[] {"MD5", "SHA-1"};
   byte encrypted[];
   byte decrypted[];
   byte plainBytes[];
   FileInputStream iStream;
   boolean simMod = true;
   File file;
   long sTime, eTime;
   CrypticObject crypt;
   
   int dataSet[][] = new int[2][10];
   XYSeriesCollection collectEncryption;
   XYSeriesCollection collectDecryption;
   final static int countAlgo = 4;
   String [] algoList = new String[]{"RSA", "AES", "BlowFish", "DES"};
   
   Algorithms.CrypticAlgo algo;
   ApplicationContext context;
   BufferedImage graph;
    public AppGUI() {
        initComponents();
        setLocationRelativeTo(null);
        //context = new ClassPathXmlApplicationContext("spring.xml");
        analPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modulePane = new javax.swing.JLayeredPane();
        simPanel = new javax.swing.JPanel();
        plainLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plainArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cipherArea = new javax.swing.JTextArea();
        cipherLabel = new javax.swing.JLabel();
        decryptedLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        decryptedArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        dTimeLabel = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        sizeField = new javax.swing.JTextField();
        techniqueCombo = new javax.swing.JComboBox();
        fileNameField = new javax.swing.JTextField();
        dUnitLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        eTimeLabel = new javax.swing.JLabel();
        algoCombo = new javax.swing.JComboBox();
        browseButton = new javax.swing.JButton();
        sizeLabel = new javax.swing.JLabel();
        eTimeField = new javax.swing.JTextField();
        dTimeField = new javax.swing.JTextField();
        eUnitLabel = new javax.swing.JLabel();
        techniqueLabel = new javax.swing.JLabel();
        algoLabel = new javax.swing.JLabel();
        analPanel = new javax.swing.JPanel();
        encryptLabel = new javax.swing.JLabel();
        decryptLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        symLabel = new javax.swing.JLabel();
        plotGraphButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        asymmetricList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        symmetricList = new javax.swing.JList();
        asymLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        moduleMenu = new javax.swing.JMenu();
        simItem = new javax.swing.JMenuItem();
        analItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        docItem = new javax.swing.JMenuItem();
        helpItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CryptoSimulator");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 768));
        setPreferredSize(new java.awt.Dimension(750, 550));
        setResizable(false);

        plainLabel.setText("Plain Text");

        plainArea.setColumns(20);
        plainArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        plainArea.setLineWrap(true);
        plainArea.setRows(5);
        jScrollPane1.setViewportView(plainArea);

        cipherArea.setEditable(false);
        cipherArea.setColumns(20);
        cipherArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        cipherArea.setLineWrap(true);
        cipherArea.setRows(5);
        jScrollPane2.setViewportView(cipherArea);

        cipherLabel.setText("Cipher Text");

        decryptedLabel.setText("Decrypted Text");

        decryptedArea.setEditable(false);
        decryptedArea.setColumns(20);
        decryptedArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        decryptedArea.setLineWrap(true);
        decryptedArea.setRows(5);
        jScrollPane3.setViewportView(decryptedArea);

        dTimeLabel.setText("Decrypition Time");

        fileLabel.setText("Input File");

        sizeField.setEditable(false);
        sizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeFieldActionPerformed(evt);
            }
        });

        techniqueCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asymmetric", "Symmetric", "Hash", "Quantum" }));
        techniqueCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techniqueComboActionPerformed(evt);
            }
        });

        fileNameField.setEditable(false);
        fileNameField.setText("No Input File selected.");
        fileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameFieldActionPerformed(evt);
            }
        });

        dUnitLabel.setText("ms");

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        eTimeLabel.setText("Encryption Time");

        algoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RSA", "ElGamal", "Elliptic-Curve" }));
        algoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoComboActionPerformed(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        sizeLabel.setText("Size of Input (KB)");

        eTimeField.setEditable(false);
        eTimeField.setText(" ");
        eTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTimeFieldActionPerformed(evt);
            }
        });

        dTimeField.setEditable(false);
        dTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTimeFieldActionPerformed(evt);
            }
        });

        eUnitLabel.setText("ms");

        techniqueLabel.setText("Cryptography Technique");

        algoLabel.setText("Algorithm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(techniqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(techniqueCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(algoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(algoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(eTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eUnitLabel)
                        .addGap(48, 48, 48)
                        .addComponent(dTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dUnitLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(browseButton)
                        .addComponent(fileLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techniqueCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(techniqueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algoLabel)
                    .addComponent(algoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTimeField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sizeLabel)
                        .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eUnitLabel)
                        .addComponent(dTimeLabel)
                        .addComponent(dTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dUnitLabel)
                        .addComponent(eTimeLabel)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout simPanelLayout = new javax.swing.GroupLayout(simPanel);
        simPanel.setLayout(simPanelLayout);
        simPanelLayout.setHorizontalGroup(
            simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simPanelLayout.createSequentialGroup()
                .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plainLabel))
                        .addGap(18, 18, 18)
                        .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cipherLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decryptedLabel)))
                    .addGroup(simPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        simPanelLayout.setVerticalGroup(
            simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plainLabel)
                    .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cipherLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(decryptedLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(6, 6, 6)
                .addGroup(simPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        analPanel.setPreferredSize(new java.awt.Dimension(1200, 400));

        encryptLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encryptLabel.setPreferredSize(new java.awt.Dimension(500, 300));

        decryptLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        decryptLabel.setPreferredSize(new java.awt.Dimension(500, 300));

        symLabel.setText("Symmetric");

        plotGraphButton.setText("Plot Graph");
        plotGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotGraphButtonActionPerformed(evt);
            }
        });

        asymmetricList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "RSA", "ElGamal", "Elliptic-Curve" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        asymmetricList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                asymmetricListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(asymmetricList);

        symmetricList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "AES", "BlowFish", "DES" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        symmetricList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                symmetricListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(symmetricList);

        asymLabel.setText("Asymmetric");

        clearButton.setText("Clear Selection");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(symLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asymLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plotGraphButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asymLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(symLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plotGraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout analPanelLayout = new javax.swing.GroupLayout(analPanel);
        analPanel.setLayout(analPanelLayout);
        analPanelLayout.setHorizontalGroup(
            analPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encryptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decryptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        analPanelLayout.setVerticalGroup(
            analPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(analPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryptLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modulePaneLayout = new javax.swing.GroupLayout(modulePane);
        modulePane.setLayout(modulePaneLayout);
        modulePaneLayout.setHorizontalGroup(
            modulePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modulePaneLayout.createSequentialGroup()
                .addComponent(simPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        modulePaneLayout.setVerticalGroup(
            modulePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(analPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(simPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modulePane.setLayer(simPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        modulePane.setLayer(analPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        moduleMenu.setText("Module");

        simItem.setText("Simulation");
        simItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simItemActionPerformed(evt);
            }
        });
        moduleMenu.add(simItem);

        analItem.setText("Analysis");
        analItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analItemActionPerformed(evt);
            }
        });
        moduleMenu.add(analItem);

        jMenuItem1.setText("BB84");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        moduleMenu.add(jMenuItem1);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        moduleMenu.add(exitItem);

        mainMenu.add(moduleMenu);

        helpMenu.setText("Help");

        docItem.setText("Documentation");
        helpMenu.add(docItem);

        helpItem.setText("Help");
        helpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modulePane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(modulePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetComponents()
    {
        setLocationRelativeTo(null);
        //Reset simPanel
        plainArea.setText("");
        cipherArea.setText("");
        decryptedArea.setText("");
        sizeField.setText("");
        eTimeField.setText("");
        dTimeField.setText("");
        fileNameField.setText("No Input File Selected.");
        techniqueCombo.setSelectedIndex(0);
        algoCombo.setModel(new DefaultComboBoxModel(asym));
        
        //Reset analPanel
        symmetricList.clearSelection();
        asymmetricList.clearSelection();
        //hashList.clearSelection();
        encryptLabel.setIcon(null);
        decryptLabel.setIcon(null);
        
    }
    private void helpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpItemActionPerformed

    private void simItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simItemActionPerformed
        // TODO add your handling code here:
        setSize(new Dimension(750, 550));
        resetComponents();
        
        simPanel.setVisible(true);
        analPanel.setVisible(false);
    }//GEN-LAST:event_simItemActionPerformed

    private void analItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analItemActionPerformed
        // TODO add your handling code here:
        setSize(new Dimension(1220, 450));
        resetComponents();
        
        simPanel.setVisible(false);
        analPanel.setVisible(true);
        
    }//GEN-LAST:event_analItemActionPerformed

    private void plotGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotGraphButtonActionPerformed
        int i, j;
        int alen, slen, hlen;
         Object asymmetric[] = asymmetricList.getSelectedValues();
         Object symmetric[] = symmetricList.getSelectedValues();
         //Object hash[] = hashList.getSelectedValues();
         alen = asymmetric.length;
         slen = symmetric.length;
         //hlen = hash.length;
         String myList[] = new String[alen+slen];
         
         j=0;
         for(i=0; i<alen; ++i)
             myList[j++] = (String)asymmetric[i];
         for(i=0; i<slen; ++i)
             myList[j++] = (String)symmetric[i];
         /*for(i=0; i<hlen; ++i)
             myList[j++] = (String)hash[i];*/
         
        if(myList.length == 0){
            JOptionPane.showMessageDialog(modulePane, "Select any technique to plot the graph.", "Empty Selection",ERROR_MESSAGE);
            return;
        }
        
        context = new ClassPathXmlApplicationContext("spring.xml");
        collectEncryption = new XYSeriesCollection();
        collectDecryption = new XYSeriesCollection();
        for(i=0; i<myList.length; ++i){
            System.out.println(myList[i]);
            algo = (CrypticAlgo)context.getBean(myList[i]);
            collectEncryption.addSeries(algo.getEncryptionDataSet());
            collectDecryption.addSeries(algo.getDecryptionDataSet());
        }
        plotGraphEncryption();
        plotGraphDecryption();
    }//GEN-LAST:event_plotGraphButtonActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void asymmetricListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_asymmetricListValueChanged
        // TODO add your handling code here:
       // System.out.println(1);
    }//GEN-LAST:event_asymmetricListValueChanged

    private void symmetricListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_symmetricListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_symmetricListValueChanged

    private void fileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameFieldActionPerformed

    private void dTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTimeFieldActionPerformed

    private void eTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTimeFieldActionPerformed

    private void sizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeFieldActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed

        if(file == null){
            plainBytes = plainArea.getText().getBytes();
        }
        int len = plainBytes.length;
        sizeField.setText(""+((float)plainBytes.length)/1024);
        context = new ClassPathXmlApplicationContext("spring.xml");
        algo_used = algoCombo.getSelectedItem().toString();       
        algo = (CrypticAlgo)context.getBean(algo_used);

        crypt = algo.encrypt(plainBytes);
        if(len < 20480)
            cipherArea.setText((""+DatatypeConverter.printHexBinary(crypt.data)).toLowerCase());
        eTimeField.setText(""+crypt.time);
        
        if(len > (1024*1024*120))
        {
            plainBytes = null;
            fileNameField.setText("No Input File selected.");
        }
            

        crypt = algo.decrypt(crypt.data);
        if(len < 20480)
            decryptedArea.setText(""+new String(crypt.data));
        dTimeField.setText(""+crypt.time);
        
        JOptionPane.showMessageDialog(modulePane, "The input has been processed successfully.", "Success",INFORMATION_MESSAGE);
    }//GEN-LAST:event_applyButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        resetComponents();
        JFileChooser openTextFile = new JFileChooser();
        int returnVal;
        String line;

        if(evt.getSource() == browseButton){

            returnVal = openTextFile.showOpenDialog(simPanel);
            if(returnVal == JFileChooser.APPROVE_OPTION){
                file = openTextFile.getSelectedFile();
                fileNameField.setText(""+file.getPath());
                try {
                    iStream = new FileInputStream(file);
                    plainBytes = new byte[iStream.available()];
                    iStream.read(plainBytes);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                sizeField.setText(""+((float)plainBytes.length)/1024);
                if(plainBytes.length < 20480)
                    plainArea.setText(new String(plainBytes));
                else
                    JOptionPane.showMessageDialog(modulePane, "This file will be processed directly owing to its large size.", "Large File",INFORMATION_MESSAGE);
              
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void techniqueComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techniqueComboActionPerformed

        String item = techniqueCombo.getSelectedItem().toString();
        decryptedArea.setText("");
        cipherArea.setText("");
        decryptedArea.setEnabled(true);
        cipherLabel.setText("Cipher Text");
        decryptedLabel.setVisible(true);
        decryptedArea.setVisible(true);
        dTimeLabel.setVisible(true);
        dUnitLabel.setVisible(true);
        dTimeField.setVisible(true);
        algoCombo.setEnabled(true);
        switch(item)
        {
            case "Asymmetric":
            algoCombo.setModel(new DefaultComboBoxModel(asym));
            break;
            case "Symmetric":
            algoCombo.setModel(new DefaultComboBoxModel(sym));
            break;
            case "Hash":
            algoCombo.setModel(new DefaultComboBoxModel(hash));
            cipherLabel.setText("Message Digest");
            decryptedLabel.setVisible(false);
            decryptedArea.setEnabled(false);
            decryptedArea.setVisible(false);
            dTimeLabel.setVisible(false);
            dUnitLabel.setVisible(false);
            dTimeField.setVisible(false);
            break;
            default:
            algoCombo.setEnabled(false);
        }
    }//GEN-LAST:event_techniqueComboActionPerformed

    private void algoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoComboActionPerformed
        // TODO add your handling code here:
        //algo_used = jComboBox2.getSelectedItem().toString();
    }//GEN-LAST:event_algoComboActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        symmetricList.clearSelection();
        asymmetricList.clearSelection();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //this.setVisible(false);
        BB84GUI obj = new BB84GUI();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void plotGraphEncryption(){
       
        
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Encryption",
                "Size of Input",
                "Encryption Time",
                collectEncryption,
                PlotOrientation.VERTICAL,
                true,
                true,
                true
        );
        
       try {
           ChartUtilities.saveChartAsJPEG(new File("chartEncrypt.jpg"), chart, 500, 300);
           showImage(encryptLabel, "chartEncrypt.jpg");
       } catch (IOException ex) {
           ex.printStackTrace();
       }
       
       
    }
    
    public void plotGraphDecryption(){
       
        
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Decryption",
                "Size of Input",
                "Decryption Time",
                collectDecryption,
                PlotOrientation.VERTICAL,
                true,
                true,
                true
        );
        
       try {
           ChartUtilities.saveChartAsJPEG(new File("chartDecrypt.jpg"), chart, 500, 300);
           showImage(decryptLabel, "chartDecrypt.jpg");
       } catch (IOException ex) {
           ex.printStackTrace();
       }
       
       
    }
    
    public void showImage(JLabel label, String imageName) throws IOException{
        BufferedImage image = ImageIO.read(new File(imageName));
        ImageIcon icon = new ImageIcon(image);
        label.setIcon(icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Security.addProvider(new BouncyCastleProvider());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algoCombo;
    private javax.swing.JLabel algoLabel;
    private javax.swing.JMenuItem analItem;
    private javax.swing.JPanel analPanel;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel asymLabel;
    private javax.swing.JList asymmetricList;
    private javax.swing.JButton browseButton;
    private javax.swing.JTextArea cipherArea;
    private javax.swing.JLabel cipherLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField dTimeField;
    private javax.swing.JLabel dTimeLabel;
    private javax.swing.JLabel dUnitLabel;
    private javax.swing.JLabel decryptLabel;
    private javax.swing.JTextArea decryptedArea;
    private javax.swing.JLabel decryptedLabel;
    private javax.swing.JMenuItem docItem;
    private javax.swing.JTextField eTimeField;
    private javax.swing.JLabel eTimeLabel;
    private javax.swing.JLabel eUnitLabel;
    private javax.swing.JLabel encryptLabel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JMenuItem helpItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu moduleMenu;
    private javax.swing.JLayeredPane modulePane;
    private javax.swing.JTextArea plainArea;
    private javax.swing.JLabel plainLabel;
    private javax.swing.JButton plotGraphButton;
    private javax.swing.JMenuItem simItem;
    private javax.swing.JPanel simPanel;
    private javax.swing.JTextField sizeField;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel symLabel;
    private javax.swing.JList symmetricList;
    private javax.swing.JComboBox techniqueCombo;
    private javax.swing.JLabel techniqueLabel;
    // End of variables declaration//GEN-END:variables
}
